import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "skin-c-1": "var(--color-base-1)",
        "skin-c-2": "var(--color-base-2)",
        "skin-c-3": "var(--color-base-3)",
        "skin-c-4": "var(--color-base-4)",
        "skin-c-5": "var(--color-base-5)",
        "skin-c-6": "var(--color-base-6)",
        "skin-c-7": "var(--color-base-7)",
        "skin-c-success": "var(--color-base-success)",
        "skin-c-danger": "var(--color-base-danger)",
        "skin-c-warning": "var(--color-base-warning)",
        "skin-c-info": "var(--color-base-info)",
      },
      fill: {
        "skin-ci-1": "var(--color-icon-1)",
        "skin-ci-2": "var(--color-icon-2)",
        "skin-ci-3": "var(--color-icon-3)",
        "skin-ci-4": "var(--color-icon-4)",
        "skin-ci-5": "var(--color-icon-5)",
        "skin-ci-6": "var(--color-icon-6)",
      },
      backgroundColor: {
        "skin-cg-1": "var(--color-bg-1)",
        "skin-cg-2": "var(--color-bg-2)",
        "skin-cg-3": "var(--color-bg-3)",
        "skin-cg-4": "var(--color-bg-4)",
        "skin-cg-5": "var(--color-bg-5)",
        "skin-cg-modal-overlay": "var(--color-bg-modal-overlay)",
        "skin-cg-header": "var(--color-bg-header)",
        "skin-cg-blur": "var(--color-bg-blur)",
        "skin-cg-disable": "var(--color-bg-disable)",
      },
      borderColor: {
        "skin-cb-1": "var(--color-border-1)",
        "skin-cb-2": "var(--color-border-2)",
        "skin-cb-3": "var(--color-border-3)",
        "skin-cb-4": "var(--color-border-4)",
      },
      textColor: {
        "skin-ct-1": "var(--color-text-1)",
        "skin-ct-2": "var(--color-text-2)",
        "skin-ct-3": "var(--color-text-3)",
        "skin-ct-4": "var(--color-text-4)",
        "skin-ct-disable": "var(--color-text-disable)",
      },
      fontSize: {
        "skin-fs-1": "var(--font-size-1)",
        "skin-fs-2": "var(--font-size-2)",
        "skin-fs-3": "var(--font-size-3)",
        "skin-fs-4": "var(--font-size-4)",
        "skin-fs-5": "var(--font-size-5)",
        "skin-fs-6": "var(--font-size-6)",
        "skin-fs-7": "var(--font-size-7)",
        "skin-fs-8": "var(--font-size-8)",
        "skin-fs-9": "var(--font-size-9)",
        "skin-fs-10": "var(--font-size-10)",
      },
      lineHeight: {
        "skin-1": "var(--line-height-1)",
        "skin-2": "var(--line-height-2)",
        "skin-3": "var(--line-height-3)",
        "skin-4": "var(--line-height-4)",
      },
      borderRadius: {
        "skin-1": "var(--border-radius-1)",
        "skin-2": "var(--border-radius-2)",
        "skin-3": "var(--border-radius-3)",
        "skin-4": "var(--border-radius-4)",
        "skin-5": "var(--border-radius-5)",
        "skin-6": "var(--border-radius-6)",
        "skin-7": "var(--border-radius-7)",
        "skin-8": "var(--border-radius-8)",
        "skin-9": "var(--border-radius-9)",
      },
      boxShadow: {
        "skin-1": "var(--box-shadow-1)",
        "skin-2": "var(--box-shadow-2)",
        "skin-3": "var(--box-shadow-3)",
        "skin-4": "var(--box-shadow-4)",
      },
      zIndex: {
        "skin-header": "var(--zindex-header)",
        "skin-modal-box": "var(--zindex-modal-box)",
        "skin-modal-overlay": "var(--zindex-modal-overlay)",
        "skin-toast": "var(--zindex-toast)",
      },
    },
  },
  plugins: [],
};
export default config;
