import type { Metadata } from "next";
import Providers from "./providers";
import fontIransansx from "@/constants/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl" data-theme="dark">
      <body
        suppressHydrationWarning={true}
        className={`${fontIransansx.className}`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
